### ISSUE TITLE
Failure to prepare mysql statements

### ISSUE THREAD

**Issue by kubevious** [kubevious/kubevious#12]
### Describe the bug
Exception in UI. Should repair broken mysql connection.

### Screenshots
```
Error: Can't add new command when connection is in closed state
    at Connection._addCommandClosedState (/app/node_modules/mysql2/lib/connection.js:137:17)
    at PreparedStatementInfo.execute (/app/node_modules/mysql2/lib/commands/prepare.js:27:29)
    at /app/node_modules/kubevious-helpers/lib/mysql-driver.js:88:23
    at Promise._execute (/app/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/app/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/app/node_modules/bluebird/js/release/promise.js:103:10)
    at MySqlDriver.executeStatement (/app/node_modules/kubevious-helpers/lib/mysql-driver.js:75:16)
    at HistorySnapshotReader._execute (/app/node_modules/kubevious-helpers/lib/history/snapshot-reader.js:405:29)
    at HistorySnapshotReader.queryTimeline (/app/node_modules/kubevious-helpers/lib/history/snapshot-reader.js:67:29)
    at /app/lib/routers/history.js:38:24
    at handleReturn (/app/node_modules/express-promise-router/lib/express-promise-router.js:24:27)
    at /app/node_modules/express-promise-router/lib/express-promise-router.js:56:9
    at handleReturn (/app/node_modules/express-promise-router/lib/express-promise-router.js:24:27)
    at /app/node_modules/express-promise-router/lib/express-promise-router.js:56:9
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
```

**Comment by kubevious** [comment]
Fixed in https://github.com/kubevious/kubevious/releases/tag/v0.6
