### ISSUE TITLE
Error: Request failed with status code 413

### ISSUE THREAD

**Issue by opvizordz** [kubevious/kubevious#14]
### Describe the bug

I installed kubevious via the latest helm chart and noticed an empty dashboard. 

Logs kubevious  pod 

```
PayloadTooLargeError: request entity too large
    at readStream (/app/node_modules/raw-body/index.js:155:17)
    at getRawBody (/app/node_modules/raw-body/index.js:108:12)
    at read (/app/node_modules/body-parser/lib/read.js:77:3)
    at jsonParser (/app/node_modules/body-parser/lib/types/json.js:135:5)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/app/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
    at /app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
    at next (/app/node_modules/express/lib/router/index.js:275:10)
    at query (/app/node_modules/express/lib/middleware/query.js:45:5)

```

kubevious-parser log files:

```
[2020-04-05 07:56:25.981 +0000] INFO  (FacadeDampener/1 on kubevious-parser-5d9f749865-6rtz5): [_tryProcessJob] empty
[2020-04-05 07:56:28.246 +0000] ERROR (ReporterTarget/1 on kubevious-parser-5d9f749865-6rtz5): [request]  Error: Request failed with status code 413
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2020-04-05 07:56:28.247 +0000] ERROR (ReporterDampener/1 on kubevious-parser-5d9f749865-6rtz5): [_processJob]  Error: Request failed with status code 413
    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
[2020-04-05 07:56:28.247 +0000] WARN  (ReporterDampener/1 on kubevious-parser-5d9f749865-6rtz5): [_tryProcessJob] last job failed

```
### To Reproduce
1. install helm chart
2. Dashboard empty
3. kubectl logs kubevious and kubevious-parser-....

### Environment Details:
 - Kubernetes Current version: 1.16.6-do.0
 - Chrome

**Comment by rubenhak** [comment]
@opvizordz, thank you for submission. Could you share some scale numbers: nodes, pods, deployments?

**Comment by rubenhak** [comment]
@opvizordz, by any chance are you using ConfigMaps that contain large pieces of payload?

**Comment by rubenhak** [comment]
@opvizordz, looks like indeed you have some k8s object which is more that 1MB in size. I've increased the size to 10MB. Anything beyond that would be skipped. Could you try the following version and let us know how it works?
```sh
helm repo add kubevious https://helm.kubevious.io
helm upgrade --atomic -i kubevious kubevious/kubevious --version 0.5.1 -n kubevious 
```

**Comment by vchain-us-mgmt** [comment]
@rubenhak thanks a lot for the quick fix. Upgrade worked and dashboard shows data.
The largest object I could find were the Grafana dashboards (0.5MB).
Is there a simple way to find all objects by size?

**Comment by opvizordz** [comment]
@rubenhak thanks a lot for the quick fix. Upgrade worked and dashboard shows data.
The largest object I could find were the Grafana dashboards (0.5MB).
Is there a simple way to find all objects by size?

**Comment by kubevious** [comment]
@opvizordz, fixed in here: https://github.com/kubevious/kubevious/releases/tag/v0.5
