### ISSUE TITLE
Error parsing containerConfig.envFrom

### ISSUE THREAD

**Issue by thelan** [kubevious/kubevious#2]
**Describe the bug**

After starting deploying to a running kubernetes cluster, the container for the kubevious deployment is throwing the foillowing error. Also this cause the UI to be empty.

```
ERROR (ConcreteRegistry/1 on kubevious-84bb6b68d7-4ncct): [_triggerChanged] TypeError: Cannot read property 'value' of undefined                                                                               
    at processContainer (/app/lib/logic/parsers/030_app-controllers.js:183:32)                                                                                                                                                                 
    at Object.handler (/app/lib/logic/parsers/030_app-controllers.js:80:17)                                                                                                                                                                    
    at LogicProcessor._processHandler (/app/lib/logic/processor.js:232:21)                                                                                                                                                                     
    at LogicProcessor._processParser (/app/lib/logic/processor.js:178:18)                                                                                                                                                                      
    at LogicProcessor._processParsers (/app/lib/logic/processor.js:164:18)                                                                                                                                                                     
    at LogicProcessor._process (/app/lib/logic/processor.js:146:14)                                                                                                                                                                            
    at EventDampener._processCb (/app/lib/utils/event-dampener.js:42:19)                                                                                                                                                                       
    at /app/lib/utils/event-dampener.js:26:29                                                                                                                                                                                                  
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)                                                                                                                                                                        
    at MappingPromiseArray._promiseFulfilled (/app/node_modules/bluebird/js/release/map.js:68:38)                                                                                                                                              
    at MappingPromiseArray.PromiseArray._iterate (/app/node_modules/bluebird/js/release/promise_array.js:115:31)                                                                                                                               
    at MappingPromiseArray.init (/app/node_modules/bluebird/js/release/promise_array.js:79:10)                                                                                                                                                 
    at MappingPromiseArray._asyncInit (/app/node_modules/bluebird/js/release/map.js:37:10)                                                                                                                                                     
    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:97:12)                                                                                                                                                                  
    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)                                                                                                                                                                       
    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)                                                                                                                                                               
    at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)                                                                                                                                    
    at processImmediate (internal/timers.js:439:21)                   
```

**To Reproduce**
1. Deploy using Helm
2. Observe logs from kubevious pod
3. Run portforward and go to the webui
4. See an empty ui and the error above in the kubevious pod logs

**Desktop (please complete the following information):**
 - OS: Fedora 30
 - Browser: Chrome
 - Version: 79.0.3945.130
 - Kubernetes version: v1.16.3

**other informations**
Although i'm not familiar with nodejs i've added a quick workaround to skip this section of code and everything else went fine.

**Comment by thelan** [comment]
After rethinking about the section of the code, there's no envObj in this if block so i think we can just skip this section.

**Comment by kubevious** [comment]
Thanks for finding!

**Comment by rubenhak** [comment]
Merged, built, released. Please don't forget to pull the [https://github.com/kubevious/deploy](https://github.com/kubevious/deploy) repo for updated charts.
