### ISSUE TITLE
MySqlDriver Error

### ISSUE THREAD

**Issue by AlexZalyalowa** [kubevious/kubevious#48]
Hello!
I've installed kubevious via helm template
`helm template --namespace kubevious . > kubevious.yaml
kubectl -n kubeious create -f kubevious.yaml`

I've got 500 errornotconnected in UI and error in  kubevious pod
`
[2020-11-05 10:14:00.968 +0000] ERROR (MySqlDriver/1 on kubevious-859c868868-hvm8k): [executeInTransaction] TX Failed.
[2020-11-05 10:14:00.969 +0000] ERROR (MySqlDriver/1 on kubevious-859c868868-hvm8k): [executeInTransaction] Rolling Back.
[2020-11-05 10:14:00.970 +0000] ERROR (MySqlDriver/1 on kubevious-859c868868-hvm8k): [executeInTransaction] Rollback complete.
[2020-11-05 10:14:00.970 +0000] ERROR (MySqlDriver/1 on kubevious-859c868868-hvm8k): [_acceptConnection] failed:  Error: Cannot find module './migrators/7'
Require stack:
- /app/lib/db/index.js
- /app/lib/context.js
- /app/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Database._processVersionMigration (/app/lib/db/index.js:114:24)
    at /app/lib/db/index.js:105:74
    at /app/node_modules/kubevious-kubik/node_modules/the-promise/lib/serial.js:9:36
    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (/app/node_modules/bluebird/js/release/reduce.js:166:18)
    at Object.gotAccum (/app/node_modules/bluebird/js/release/reduce.js:155:25)
    at Object.tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/app/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)
[2020-11-05 10:14:00.970 +0000] INFO  (MySqlDriver/1 on kubevious-859c868868-hvm8k): [_disconnect]

`
mysql pod is up and statefulset is ready.
### Environment Details:
 - Kubernetes version
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea", GitTreeState:"clean", BuildDate:"2020-03-12T20:55:23Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
 - Browser furefox
 - Version [e.g. v0.3]

**Comment by rubenhak** [comment]
hi @AlexZalyalowa, looks like you're using latest unofficial build which has some issues. I'd recommend the following:
1. Remove existing installation, including the mysql & volume
2. Install version 0.6.36 using helm install (not helm template, then kubectl apply) following the instructions here: [https://github.com/kubevious/helm#installing-the-chart-using-helm-v3x](https://github.com/kubevious/helm#installing-the-chart-using-helm-v3x)

If you want to wait few days, there will be a new version released that has a lot of improvements. The new version will not be upgradable from previous ones (long story), so unfortunately uninstallation would have to be done anyways.

**Comment by kubevious** [comment]
Resolved in [v0.7](https://github.com/kubevious/kubevious/releases/tag/v0.7).
