### ISSUE TITLE
Backend and Parser craches with null access exception

### ISSUE THREAD

**Issue by Simon-Boyer** [kubevious/kubevious#88]
### Describe the bug

Just tried deploying this using the helm chart, but I am getting this error on both the backend and the parser pods:

```
2023-12-02 22:30:33.966] ERROR (backend): [run] stage: TypeError: Cannot read properties of null (reading 'join')
    at ClusterInfoFetcher._setupApiGroup (/app/node_modules/k8s-super-client/dist/cluster-info-fetcher.js:118:162)
    at /app/node_modules/k8s-super-client/dist/cluster-info-fetcher.js:112:27
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 44) Failed. Reason:
    arg0: "Error: Cannot read properties of null (reading 'join')"
[2023-12-02 22:30:33.966] ERROR (backend): [execute] run :: Failed. Reason:
    arg0: [
      {}
    ]
[2023-12-02 22:30:33.967] ERROR (backend): [_handleError] Reason:
    arg0: [
      {}
    ]
```

The pod then crashes. Everything else in my environment looks healthy. If I open the UI, I get a 502 error.

Logs for the backed:
[kubevious.txt](https://github.com/kubevious/kubevious/files/13537528/kubevious.txt)

Logs for the parser:
[kubevious(1).txt](https://github.com/kubevious/kubevious/files/13537530/kubevious.1.txt)

### To Reproduce
1. Deploy version 1.2.1 using helm

### Expected behavior
Everything is healthy and working.

### Screenshots
N/A

### Environment Details:
 - Talos OS version 1.5.2
 - Kubernetes version: v1.27.3
 - Kubevious version 1.2.1
 - Using ArgoCD to manage the helm deployment

### Additional context
N/A

**Comment by rubenhak** [comment]
hi @Simon-Boyer, could you post the output for following API queries?
`GET https://<k8s-api-server>/apis/subresources.kubevirt.io/v1`
and 
`GET https://<k8s-api-server>/apis/argoproj.io/v1alpha1`

**Comment by Simon-Boyer** [comment]
```
❯ curl http://localhost:8080/apis/subresources.kubevirt.io/v1
404 page not found

❯ curl http://localhost:8080/apis/argoproj.io/v1alpha1
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "argoproj.io/v1alpha1",
  "resources": [
    {
      "name": "applicationsets",
      "singularName": "applicationset",
      "namespaced": true,
      "kind": "ApplicationSet",
      "verbs": [
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "create",
        "update",
        "watch"
      ],
      "shortNames": [
        "appset",
        "appsets"
      ],
      "storageVersionHash": "aaUQCD/yGd0="
    },
    {
      "name": "applicationsets/status",
      "singularName": "",
      "namespaced": true,
      "kind": "ApplicationSet",
      "verbs": [
        "get",
        "patch",
        "update"
      ]
    },
    {
      "name": "appprojects",
      "singularName": "appproject",
      "namespaced": true,
      "kind": "AppProject",
      "verbs": [
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "create",
        "update",
        "watch"
      ],
      "shortNames": [
        "appproj",
        "appprojs"
      ],
      "storageVersionHash": "aI45W0YuhVE="
    },
    {
      "name": "applications",
      "singularName": "application",
      "namespaced": true,
      "kind": "Application",
      "verbs": [
        "delete",
        "deletecollection",
        "get",
        "list",
        "patch",
        "create",
        "update",
        "watch"
      ],
      "shortNames": [
        "app",
        "apps"
      ],
      "storageVersionHash": "PVzHEyjMffI="
    }
  ]
}
```

**Comment by rubenhak** [comment]
@Simon-Boyer, please try the version 1.2.2:
```
helm repo update
helm upgrade --atomic -i kubevious kubevious/kubevious --version 1.2.2 -n kubevious
```
