### ISSUE TITLE
Incorrect handling of in-cluster IPv6 kube-apiserver address.

### ISSUE THREAD

**Issue by cehoffman** [kubevious/kubevious#90]
### Describe the bug

Running kubevious on a dual IP stack cluster where IPv6 is the primary address space results in an invalid URL to the apiserver.

### Expected behavior
Successful connection to in cluster api server service.

### Screenshots

Environment variables for the kubernetes service in cluster.
~~~
KUBERNETES_PORT=tcp://[fd00:beef::1]:443
KUBERNETES_SERVICE_PORT=443
KUBERNETES_PORT_443_TCP_ADDR=fd00:beef::1
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP=tcp://[fd00:beef::1]:443
KUBERNETES_SERVICE_PORT_HTTPS=443
KUBERNETES_SERVICE_HOST=fd00:beef::1
~~~

Logs from backend, but parser has the same error.
~~~
[2024-07-28 23:19:50.480] INFO (backend): [run] stage: connect-to-k8s. Begin
[2024-07-28 23:19:50.480] INFO (backend): [construct]
[2024-07-28 23:19:50.484] WARN (backend): [request] Failed. Method: GET. Connection Error:  TypeErro
    at new NodeError (node:internal/errors:399:5)
    at new URL (node:internal/url:560:13)
    at dispatchHttpRequest (/app/node_modules/axios/dist/node/axios.cjs:2627:20)
    at /app/node_modules/axios/dist/node/axios.cjs:2564:5
    at new Promise (<anonymous>)
    at wrapAsync (/app/node_modules/axios/dist/node/axios.cjs:2544:10)
    at http (/app/node_modules/axios/dist/node/axios.cjs:2570:10)
    at Axios.dispatchRequest (/app/node_modules/axios/dist/node/axios.cjs:3530:10)
    at Axios.request (/app/node_modules/axios/dist/node/axios.cjs:3886:33)
    at wrap (/app/node_modules/axios/dist/node/axios.cjs:29:15)
[2024-07-28 23:19:50.485] ERROR (backend): [run] stage: [object Object] Failed. Reason:
[2024-07-28 23:19:50.485] ERROR (backend): [execute] run :: Failed. Reason:
    arg0: [
      {
        "status": 0,
        "message": "Invalid URL",
        "method": "GET",
        "baseURL": "https://fd00:beef::1:443",
        "url": "/api"
      }
    ]
[2024-07-28 23:19:50.485] ERROR (backend): [_handleError] Reason:
    arg0: [
      {
        "status": 0,
        "message": "Invalid URL",
        "method": "GET",
        "baseURL": "https://fd00:beef::1:443",
        "url": "/api"
      }
    ]
~~~

### Environment Details:
 - Kubernetes Distribution/Version [e.g. GKE v1.13.12-gke.25, OpenShift 4.3] Talos 1.7.5 Kubernetes 1.29.6
 - Version [e.g. v0.3] 1.2.1

**Comment by cehoffman** [comment]
The base URL in this instance should be `https://[fd00:beef::1]:443`

Edit:

Using the typically correct `[]` form also doesn't seem to work when passing it in as an explicit override to `KUBERNETES_SERVICE_HOST`.

It tries to do a DNS lookup on that.

~~~
[2024-07-28 23:38:19.416] ERROR (parser): [_handleError] Reason:
    arg0: [
      [
        {
          "status": 0,
          "message": "getaddrinfo ENOTFOUND [fd00:beef::1]",
          "method": "GET",
          "baseURL": "https://[fd00:beef::1]:443",
          "url": "/api"
        }
      ]
    ]
[Backend::close]
~~~

Changing to use the in-cluster DNS endpoint (`kubernetes.default.svc`) when overriding `KUBERNETES_SERVICE_HOST` works.

**Comment by rubenhak** [comment]
@cehoffman, thanks for submitting this issue. I see you hit another IPv6 issue with redis (https://github.com/kubevious/kubevious/issues/91). As I said over there, it would take some time to resolve this. 

Can I ask, how did you override the KUBERNETES_SERVICE_HOST?

**Comment by cehoffman** [comment]
Thanks for look at it. I'll respond to your suggestion on the other issue.

For `KUBERNETES_SERVICE_HOST` this is set as an explicit environment variable for the container in the respective deployments. This is how cilium overrides the values when set so that standard libraries used within a container context do not have to be explicitly configured. For a port change it uses `KUBERNETES_SERVICE_PORT`.
